services:
  php:
    image: webdevops/php-nginx-dev:8.4
    working_dir: /app
    volumes:
      - ./:/app
      - ./.docker/vhost.conf:/opt/docker/etc/nginx/vhost.conf
      - ./.docker/php.webdevops.ini:/opt/docker/etc/php/php.webdevops.ini
    user: 1000:1000
    ports:
      - '8090:80'
  redis:
    image: redis
    volumes:
      - 'redisdata:/data'

  db:
    image: mariadb
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: kolejki
      MYSQL_USER: kolejki
      MYSQL_PASSWORD: kolejki
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - 'dbdata:/var/lib/mysql'
  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8091:80
    environment:
      UPLOAD_LIMIT: 300M

volumes:
  dbdata:
    driver: local
  redisdata:
    driver: local
